spring:
  main:
    allow-circular-references: true
  liquibase:
    change-log: classpath:/schema.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://java_postgres_db:5432/java_postgres_db
#    url: jdbc:postgresql://localhost:5432/java_postgres_db
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver

prefix-service:
  version: v1