spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    change-log: classpath:/schema.xml
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://java_postgres_db:5432/java_postgres_db
#    url: jdbc:postgresql://localhost:5432/java_postgres_db
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver

prefix-service:
  version: v1